version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - pwd
      - ls -la
      - find . -name "PersonalAppFrontend" -type d
      - cd PersonalAppFront/PersonalAppFrontend
      - npm install
      - export BUCKET_NAME=erikmabes-com-$(aws sts get-caller-identity --query Account --output text)
  build:
    commands:
      - pwd
      - ls -la
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET_NAME/ --delete
